# SPDX-FileCopyrightText: 2023 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
coverage:
  range: 50..80
  round: down
  precision: 2

ignore:
  - "*_test.go"
  - "vendor"

fixes:
  - "github.com/xmidt-org/caduceus/::"
