## SPDX-FileCopyrightText: 2023 Comcast Cable Communications Management, LLC
## SPDX-License-Identifier: Apache-2.0

version: "2"
linters:
  enable:
    - bodyclose
    - dupl
    - errorlint
    - goconst
    - gosec
    - misspell
    - prealloc
    - unconvert
  disable:
    - errcheck
    - ineffassign
  settings:
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
        path: _test.go
      - path: main\.go
        text: 'G402:'
      - path: main\.go
        text: 'G108:'
      - path: outboundSender\.go
        text: 'G505:'
      - path: outboundSender\.go
        text: wrp.MimeTypeWrp is deprecated
      - path: outboundSender\.go
        text: 'G404:'
      - path: outboundSender\.go
        text: Consider preallocating `events`
      - path: outboundSender\.go
        text: response body must be closed
        source: .*xhttp.RetryTransactor.*
      - linters:
          - goconst
        path: outboundSender_test\.go
      - path: senderWrapper_test\.go
        text: '`fn` is unused'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
