# SPDX-FileCopyrightText: 2023 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: 'Dependabot auto approval'

on:
  pull_request_target:

permissions:
  pull-requests: write
  contents: write

jobs:
  approve:
    # yamllint disable-line
    uses: xmidt-org/shared-go/.github/workflows/approve-dependabot.yml@7b10cbd74790a5af49be5755ff835a229d2896af # v4.12.3
    secrets: inherit
