# SPDX-FileCopyrightText: 2023 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: 'Dependabot auto approval'

on:
  pull_request_target:

permissions:
  pull-requests: write
  contents: write

jobs:
  approve:
    # yamllint disable-line
    uses: xmidt-org/shared-go/.github/workflows/approve-dependabot.yml@bfcee2e5632b9b052e8176a73a9523f226ba7ef4 # v4.12.15
    secrets: inherit
