# SPDX-FileCopyrightText: 2023 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: 'Dependabot auto approval'

on:
  pull_request_target:

permissions:
  pull-requests: write
  contents: write

jobs:
  approve:
    # yamllint disable-line
    uses: xmidt-org/shared-go/.github/workflows/approve-dependabot.yml@fe1aac86f0c6b5070e7bda262d3c31cb53cc510c # v4.12.8
    secrets: inherit
