# SPDX-FileCopyrightText: 2024 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: 'Auto Release'

on:
  schedule: # Run every day at 12:00 UTC
    - cron: '0 12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    # yamllint disable-line
    uses: xmidt-org/shared-go/.github/workflows/auto-releaser.yml@4e438061d0a0f0cc5d2ecdfd27857164e003a228 # v4.11.4
    secrets: inherit
