# SPDX-FileCopyrightText: 2024 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: 'Auto Release'

on:
  schedule: # Run every day at 12:00 UTC
    - cron: '0 12 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    # yamllint disable-line
    uses: xmidt-org/shared-go/.github/workflows/auto-releaser.yml@addd969b1833260e1193fcd77ab1a6d0edc1ef07 # v4.12.16
    secrets: inherit
