# SPDX-FileCopyrightText: 2023 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: 'PROJ: xmidt-team'

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  proj:
    # yamllint disable-line
    uses: xmidt-org/shared-go/.github/workflows/proj.yml@22e2a0c03b721abb18f44828d67e41b5b3ed9f94 # v4.12.4
    secrets: inherit
