# SPDX-FileCopyrightText: 2023 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: 'PROJ: xmidt-team'

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  proj:
    # yamllint disable-line
    uses: xmidt-org/shared-go/.github/workflows/proj.yml@7b10cbd74790a5af49be5755ff835a229d2896af # v4.12.3
    secrets: inherit
